version: '3.8'

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "2000:2000"
    environment:
      - PORT=2000
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
